### ISSUE TITLE
Foreground skin no longer works as of MW1.32 due to removal of the wfRunHooks() function

### ISSUE THREAD

**Issue by AyaJulia** [jthingelstad/foreground#341] opened 2019-01-27 17:09 UTC
### Setup

- Browsers and versions:Irrelevant
- MediaWiki version:1.32
- Database version:5.6.41
- PHP version:7.2.14
- Foreground version:2.1.0
- Extension version (if connected to the issue):N/A

### Issue

Page renders correctly until wfRunHooks() is called, at which point the following appears in the page's "view source":

<b>Fatal error</b>:  Uncaught Error: Call to undefined function wfRunHooks() in /home/username/public_html/wikiname/skins/Foreground/Foreground.skin.php:202
--
  | Stack trace:
  | #0 /home/username/public_html/wikiname/includes/skins/SkinTemplate.php(227): foregroundTemplate-&gt;execute()
  | #1 /home/username/public_html/wikiname/includes/OutputPage.php(2706): SkinTemplate-&gt;outputPage()
  | #2 /home/username/public_html/wikiname/includes/exception/MWExceptionRenderer.php(136): OutputPage-&gt;output()
  | #3 /home/username/public_html/wikiname/includes/exception/MWExceptionRenderer.php(53): MWExceptionRenderer::reportHTML(Object(Error))
  | #4 /home/username/public_html/wikiname/includes/exception/MWExceptionHandler.php(98): MWExceptionRenderer::output(Object(Error), 2)
  | #5 /home/username/public_html/wikiname/includes/exception/MWExceptionHandler.php(172): MWExceptionHandler::report(Object(Error))
  | #6 /home/username/public_html/wikiname/includes/exception/MWExceptionHandler.php(144): MWExceptionHandler::handleException(Object(Error))
  | #7 [internal function in <b>/home/username/public_html/wikiname/skins/Foreground/Foreground.skin.php</b> on line <b>202</b><br />

Further investigation reveals the obvious cause at https://www.mediawiki.org/wiki/Manual:GlobalFunctions.php#wfRunHooks()

> Removed in 1.32

**Comment by Hutchy68** [comment] 2019-01-27 18:09
Duplicate of #338

**Closed by Hutchy68** 2019-01-27 18:09 UTC
