### ISSUE TITLE
Select Dropdown not working on touch devices

### ISSUE THREAD

**Issue by nischayn22** [jthingelstad/foreground#336] opened 2018-12-29 11:37 UTC
### Setup

- Browsers and versions: Mobile Devices with Latest Chrome
- MediaWiki version: NA
- Database version: NA
- PHP version: NA
- Foreground version: 2.1
- Extension version (if connected to the issue):

### Issue

Detailed description of the issue goes here.

Select Dropdown were not working on touch/mobile devices. I found out that fastclick.js was handling the 'touchstart' event. Removing this library solved the problem for me.

**Comment by Hutchy68** [comment] 2019-03-08 20:42
I can't confirm this. I do not see an issue with mobile and touch for dropdowns, menu or action button. Could you be more specific? Do you have another JS script from an extension causing an issue?

**Comment by nischayn22** [comment] 2019-03-09 08:27
So I updated Foreground recently and started to see this problem. A basic HTML <select> stopped working for me on touch devices. I don't think that it was caused by another extension as those files remained the same but there could be some conflict. However, I did debug deeper and could fix it by removing fastclick.js

**Comment by Hutchy68** [comment] 2019-03-09 14:05
There’s a bigger issue as Foundation 5 is supposed to be incompatible with jQuery 3. Which could be causing quirky issues.

**Comment by Hutchy68** [comment] 2019-03-12 15:03
Ok, compatibility seems not to be the issue since MW 1.32 is also loading `jmigrate.js` too. I still can't reproduce the issue, but ` fastclick.js` really isn't necessary anymore as all modern devices handle the 300ms delay now solved by `fastclick.js`. 

I removed `fastclick.js` and a few other unused vendor related js items. The `develop` branch should now contain the fixes. Let me know if you see any issues. Thanks.

**Comment by Hutchy68** [comment] 2020-12-13 22:44
Fixed and merged in on Mar 12, 2019. Closing as solved.

**Closed by Hutchy68** 2020-12-13 22:44 UTC
Labels: bug, solved
